apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: tamirbi/flask-contacts-devops:latest    # ✅ Ensure this is correct!
          ports:
            - containerPort: 5053
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: DB_Host
              value: "mysql"  # ✅ FIXED: Use `mysql-service`, NOT `mysql_service`
            - name: DB_User
              value: "root"
            - name: DB_Password
              value: "admin"
            - name: DB_Name
              value: "contacts_app"
            - name: DB_PORT
              value: "3306"