apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql  # 🔥 This should match the MySQL pod labels (not `flask-app`)
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3306   # ✅ Ensure this is 3306
      targetPort: 3306  # ✅ Ensure this is 3306
