apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5053   # ✅ External Port (for clients)
      targetPort: 5053  # ✅ Must match Flask container port
